import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
/**
 * App Router는 파일 시스템 기반으로 작동하며,
 * 'app' 디렉토리 내의 'page.tsx' 파일은
 * 홈페이지('/')로 인식되는데, 이는 Next.js에서
 * 사용되는 정해진 파일명 규칙입니다.
 */
